CXX=g++

heap: heap.cpp
	$(CXX) heap.cpp -o h
	./h

hash: hash.cpp
	$(CXX) hash.cpp -o hash
	./hash
heapsort: heapsort.cpp
	$(CXX) heapsort.cpp -o sort
	./sort
	
freqcount: freqcount.cpp
	$(CXX) freqcount.cpp -o f
	./f
	
hashp:hashperformance.cpp
	$(CXX) hashperformance.cpp -o hap
	./hap
	
heapp:heapPerformance.cpp
	$(CXX) heapPerformance.cpp -o heapp
	./heapp
clean:
	rm -f h hash sort f hap heapp 
